### PR TITLE
Add comment style and indentation pattern

### PR DESCRIPTION
**Pull request by tomlau10**
This language-smali plugin is great and helps a lot when editing smali codes generated from apktool using Atom!
This pull request adds comment style and indentation patterns such that atom can comment correctly when toggling line comment.

### CODE REVIEW

**Comment by xingrz** [comment]
Hope I'm not too late. Thank you @tomlau10

**Comment by xingrz** [comment]
By the way. Since this package is based on [ShaneWilton/sublime-smali](https://github.com/ShaneWilton/sublime-smali) for Sublime Text. Please also make a pull request to it if necessary. 😉

**Comment by xingrz** [comment]
Released v0.1.1. Thank you very much!

**Comment by tomlau10** [comment]
You're welcome :wink:

**Pull request merged**
